---
title: "Group_07_Analysis"
author: "Group 7"
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: yes
  html_document:
    df_print: paged
fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval = TRUE, warning = FALSE, message = FALSE, comment = NA)
```

```{r libraries}
library(tidyverse)
library(moderndive)
library(skimr)
library(kableExtra)
library(gridExtra)
library(broom)
```

```{r data}
film <- read.csv("dataset7.csv") 
# Split output Y into 2 groups >7 and <=7  
film <- film %>% 
  mutate(Rate = ifelse(film$rating >7 , ">7" ,"<=7"))%>%
  mutate_at(vars(Rate ) , funs(factor))
# Find NA observations 
# There are 92 missing data 

film %>% 
   select(rating) %>%
  summary()

ggplot(film, aes(x=rating)) + 
   geom_histogram(col="white",fill="wheat4")+
   ggtitle("Density Of Rating")+
   labs(y="frequency")+
   scale_x_continuous(name="Rating", limits=c(0, 10),n.breaks = 10)+
   theme_light()

```


```{r}
  
# Genre Variable #
#================#

# Contingency Table 

film %>% 
     tabyl(Rate, genre) %>% 
     adorn_percentages() %>% 
     adorn_pct_formatting() %>% 
     adorn_ns() 

 ggplot ( film , aes(x= Rate, y= ..prop.., group= genre,fill=genre)) + 
   geom_bar(col ="white" , position="dodge",stat = "count") + 
   scale_fill_descrete()+
   labs(x="Rate" , "y=Proportion")+
   theme_light()
```
 
 
```{r}
# Budget # 
#=========#
ggplot( film , aes( x= Rate , y= budget,fill=Rate )) + 
   geom_boxplot() +
   scale_fill_manual(values=c("blue4", "lightblue"))+
   labs(x="Ratings" , y =paste("Budget (in $ 10 ^{3} 's"))+
   theme_light()


```

```{r}
# Length # 
#==========# 

summary(film$length)  # There are 92 missing data 

dim(na.omit(film[  film$length >100 & film$Rate==">7",] ))[1]

ggplot(film , aes(x= Rate , y= log(length), fill = Rate)) + 
   geom_boxplot() +
   scale_fill_manual(values=c("blue4", "lightblue"))+
   labs(x="Ratings" , y ="Length (in minutes)")+
   theme_light()

ggplot( film , aes(x = Rate , y = year )) + 
  geom_boxplot()
  



```
```{r}

# Positive Votes # 
#=================#
 ggplot(film , aes(y= log(votes) , x= Rate , fill=Rate )) + 
   geom_boxplot() + 
   scale_fill_discrete()+
   labs(x="Rate" , y = "Number of Positive Votes")+
   theme_light()
```

```{r model}
# Now genre is categorical while lenght is numerical 
 model <- glm( Rate ~ genre + length , data = film , 
               family = binomial(link = "logit"))
 summary(model)

```

# Introduction {#sec:Intro}




# Exploratory Data Analysis {#sec:EDA}

```{r summary}
my_skim <- skim_with(base = sfl(n = length))
film%>%
  select(-c(1,6)) %>% 
  my_skim() %>% 
  transmute(Variable=skim_variable, Mean=numeric.mean, SD=numeric.sd,
            Min=numeric.p0, Q1=numeric.p25, Median=numeric.p50, Q3=numeric.p75,Max=numeric.p100,
            IQR = numeric.p75-numeric.p50) %>% 
  kable(caption = '\\label{tab:summary}Summary statistics of variables in the data set.' ,
        booktabs = TRUE, linesep = "", digits = 3) %>%
  kable_styling(font_size = 10, latex_options = "hold_position")
```

```{r}
table(film$genre)
```

```{r boxplot ,out.width='68%', fig.pos="H",fig.align='center', fig.cap="\\label{fig:boxplot}  IMDB rating by genre"}
ggplot(film, aes(genre,rating))+
  geom_boxplot(fill="SpringGreen3")+
  labs(x="Genre",y=" IMDB rating")+
  theme_light()
```

```{r}
film7 <- subset(film,rating>=7)
```

# Formal Data Analysis {#sec:FDA}


# Conclusion and further task {#sec:Conclude}
